"""Selling psychology for Partner World: ten buyers and the habits that win them.

Source: Station Collections Blueprint (artifact Kff3noKnY8qbXfebDpn474, Part 2 "Ten buyers", 2026-10-04), cut down to what a partner can
say on a phone call TODAY, then reviewed three ways on 2026-10-05 (guide fact-check, veteran sales coach, usability).
Every line below obeys the partner rules in the live guide (research/guide.md):
- US English, short spoken sentences. Every "say" is at most two sentences and ends with a question, so the owner talks next.
- No promised result, no "pays for itself", no invented statistic, no promised go-live day, no compliance promise.
- Never "you won't have to do anything": the owner still books an onboarding call and has hours / Google link ready.
- Nothing about site features that are not live yet (language switch, "hear it answer" recordings, About page, multi-location stepper).
- The partner never sets anything up, never takes a customer list, and never quotes outside the published catalogue.
- "Does it work with X?" and "do you do Y?" for anything not in the guide: "Station can confirm that", never a flat yes or no.
build_data.py ships this as PW.buyers and PW.playbook. Edit the words here, never in data.js.
"""

# fit = a box id in data.js (bundle-answer = the Answer collection, bundle-custom = Max)
BUYERS = [
    {'id': 'jaylen', 'name': 'Jaylen', 'age': 24, 'line': 'Mobile car detailer, runs it from Instagram DMs',
     'trades': 'Detailing, mobile services, anyone starting out with no website',
     'fit': 'bundle-answer', 'fitNote': 'Answer, $297 a month, website free',
     'feels': 'He just lost a job to someone who answered faster. Bookings are scattered across DMs, texts and a form, and he’s not sure he’s big enough for software.',
     'ask': 'When a customer messages you at night, how long before they hear back?',
     'say': 'Station’s Answer plan texts back anyone you miss and lets customers book themselves, and a website comes free. It’s $297 a month. Would that fix the late replies?',
     'worry': '“I’m too small for this.”',
     'reply': 'That’s what the 14-day free trial is for. There’s no contract and no setup fee, so you can try it before you pay anything. Want the page so you can look?',
     'avoid': 'Don’t lead with Core or Pro. A new owner hears $1,297 and stops listening. Start with the smallest thing that fixes the missed message.'},
    {'id': 'chen', 'name': 'Mr. Chen', 'age': 61, 'line': 'Takeout and convenience store, limited English, daughter helps',
     'trades': 'Family shops, restaurants, owners who don’t read English easily',
     'fit': 'bundle-getfound', 'fitNote': 'Get Found, $497 a month, website free',
     'feels': 'He doesn’t trust anything he can’t call. Google may show old hours and two bad reviews. Long words and fine print feel like a trap.',
     'ask': 'Do you know what hours Google shows for your shop?',
     'say': 'Station’s Get Found plan keeps your Google listing correct and asks happy customers for reviews. It’s $497 a month, with no contract. May I email the page to your daughter?',
     'worry': '“I need to ask my daughter.”',
     'reply': 'Of course. When is a good time to reach you both? I’ll email the page with the price and what’s included, so she can read it with you.',
     'avoid': 'No idioms and no fast talk. Say the price once, slowly, and say “no contract.” The person who decides may not be the one on the phone, so ask when his daughter is there.'},
    {'id': 'dave', 'name': 'Dave', 'age': 47, 'line': 'HVAC and plumbing owner, four techs, under a house all day',
     'trades': 'Plumbers, HVAC, roofers, electricians, garage doors',
     'fit': 'bundle-answer', 'fitNote': 'Answer, $297 a month; the AI receptionist is $297 more',
     'feels': 'A homeowner just told him “I called you first and nobody answered.” Calls go to voicemail while he’s under a house, and he wonders how many callers moved on.',
     'ask': 'When you’re under a house and the phone rings, what happens to that caller?',
     'say': 'Station’s Answer plan texts back anyone you miss, and the AI receptionist can answer the call itself. You keep your own number, it just forwards. Which would help more, the text or the answering?',
     'worry': '“Will it sound like a robot?” or “Does it work with Housecall Pro?”',
     'reply': 'It’s an automated assistant, and I won’t pretend otherwise. It answers from your business facts, doesn’t make up prices, and always offers to transfer the caller to a person. For Housecall Pro, Station can confirm how it fits. I don’t want to guess.',
     'avoid': 'Don’t promise a number of booked jobs. Ask who handles the books: if it’s his wife, include her. Say “forwards,” never “port.”'},
    {'id': 'brianna', 'name': 'Brianna', 'age': 34, 'line': 'Salon and med-spa owner, lives on Instagram, already pays for a booking app',
     'trades': 'Salons, spas, barbers, studios, anyone with a list of past clients',
     'fit': 'bundle-followup', 'fitNote': 'Follow Up, $427 a month, website free',
     'feels': 'She spots cheap-looking marketing instantly. She worries a new tool will clash with the booking app she already pays for, and she has past clients she never contacts.',
     'ask': 'When did you last reach out to clients who haven’t been in for a while?',
     'say': 'Station’s Follow Up plan sends a win-back email campaign to your past clients. It’s email first, so do you have their email addresses?',
     'worry': '“Does this replace my booking system?” or “Does it work with Vagaro?”',
     'reply': 'Follow Up isn’t a booking app. It’s for bringing people back. Station can confirm how it sits beside Vagaro, and I don’t want to guess.',
     'avoid': 'Don’t pitch booking to someone who already has it. And never ask her to send you her client list: it goes to Station directly, after she signs up.'},
    {'id': 'karen', 'name': 'Karen', 'age': 44, 'line': 'Practice manager at a two-dentist office; the doctor signs off',
     'trades': 'Dental, chiropractic, clinics, any office where one person researches and another approves',
     'fit': 'bundle-followup', 'fitNote': 'Follow Up, $427 a month, website free',
     'feels': 'She’ll be blamed if anything goes wrong, so she’s looking for reasons to say no. She needs something she can forward to the doctor.',
     'ask': 'When a patient doesn’t rebook, does anyone follow up?',
     'say': 'Station’s Follow Up plan emails past patients and follows up on new inquiries. It’s $427 a month with no contract. Who would need to see the page before you could try it?',
     'worry': '“Is it HIPAA compliant?”',
     'reply': 'I can’t answer that, and I won’t guess. Please email Station at main@station.solutions and ask for the answer in writing.',
     'avoid': 'Never say it’s HIPAA compliant, fine for patient health information, or make any compliance promise. Send the page and have her ask Station in writing.'},
    {'id': 'marcus', 'name': 'Marcus', 'age': 36, 'line': 'Independent gym owner, ads bring leads, front-desk staff keep turning over',
     'trades': 'Gyms, studios, anyone paying for ads whose leads go cold',
     'fit': 'bundle-followup', 'fitNote': 'Follow Up $427; Core $1,297 if he wants it all handled',
     'feels': 'Leads from his ads come in at night and nobody calls them until two days later. Staff forget. He’d like the front desk to stop being his problem.',
     'ask': 'When someone fills in a form at night, how soon do they hear from you?',
     'say': 'Station’s Follow Up plan contacts new leads automatically so they don’t go cold. It’s $427 a month with a 14-day free trial. Would that fix the night leads?',
     'worry': '“I want the whole front office off my plate.”',
     'reply': 'Then Core is every product except Radar, set up by Station, at $1,297 a month with a 30-day money-back guarantee on the first month. Bought one by one that would be $1,899. Want the page for both?',
     'avoid': 'Never say he won’t have to do anything. He’ll book a short onboarding call and have his hours and Google link ready. Don’t jump to Core unless he asks for everything.'},
    {'id': 'rosa', 'name': 'Rosa and Javier', 'age': 45, 'line': 'Family taqueria and catering, phones ring during the lunch rush',
     'trades': 'Restaurants, caterers, food trucks, family businesses with a busy rush',
     'fit': 'bundle-answer', 'fitNote': 'Answer, $297 a month, website free',
     'feels': 'During the lunch rush nobody can answer, and a catering inquiry goes to voicemail. One handles everything online at night; the other decides about money.',
     'ask': 'When the phone rings in the middle of the lunch rush, what happens?',
     'say': 'Station’s Answer plan texts back every caller you miss, so a catering inquiry gets an answer. It’s $297 a month with a 14-day free trial. Who decides about something like this, you or Javier?',
     'worry': '“Do you take online orders?”',
     'reply': 'Online ordering isn’t one of the products I know of, so I won’t guess. I can ask Station. What Answer does is text back the callers you miss.',
     'avoid': 'Ask for a time when both of them can listen. Don’t promise anything the page doesn’t say.'},
    {'id': 'linda', 'name': 'Linda', 'age': 57, 'line': 'Independent realtor or insurance agent, 1,200 past clients in a spreadsheet',
     'trades': 'Realtors, insurance, financial advisors, any business built on referrals',
     'fit': 'bundle-followup', 'fitNote': 'Follow Up, $427 a month, website free',
     'feels': 'She knows she should stay in touch with past clients and never does. New leads wait hours for a reply while she’s out. Three different email products look like a puzzle.',
     'ask': 'When a new lead comes in while you’re out showing a house, how soon do they hear back?',
     'say': 'Station’s Follow Up plan follows up with new leads right away and sends a win-back campaign to your past clients. It’s $427 a month. Which one matters more to you?',
     'worry': '“Is it legal to text my clients?”',
     'reply': 'Email goes to past clients, and texts only go to people who agreed to get them. For the details, Station can answer in writing at main@station.solutions.',
     'avoid': 'Don’t describe three products. Describe one job: keeping leads and past clients from going cold.'},
    {'id': 'tom', 'name': 'Tom', 'age': 52, 'line': 'Commercial cleaning (B2B), paid an SEO agency for a year and got nothing',
     'trades': 'Commercial cleaning, janitorial, B2B trades that bid on contracts',
     'fit': 'radar', 'fitNote': 'Radar, $297 a month',
     'feels': 'He’s been burned by marketing and assumes everyone is a scam. He checks who is behind it before he listens.',
     'ask': 'Have you worked with a marketing company before, and what happened?',
     'say': 'I’m an independent partner, and I earn a commission, so I’ll be straight with you. Station’s Radar finds businesses that fit what you sell and starts the outreach, at $297 a month, no contract. Can I send the page so you can check it out?',
     'worry': '“How do I know this isn’t another agency?”',
     'reply': 'You shouldn’t take my word for it. Station is Station Automations Group LLC in Houston, every price is published, and there’s no contract. You can also book Station’s free 15-minute intro call at station.solutions/book.',
     'avoid': 'Don’t sell fast or claim results. For him, honesty about the commission and the company is the pitch. Bring up Get Found only if he asks about Google.'},
    {'id': 'priya', 'name': 'Priya', 'age': 40, 'line': 'Operations director for a three-location auto repair group',
     'trades': 'Multi-location groups, franchises, anyone who buys on a quote',
     'fit': 'bundle-core', 'fitNote': 'Core plus extra location packs, $397 a month each',
     'feels': 'She reports to an owner and needs one clear number for a budget. She’s been burned by annual contracts with onboarding fees.',
     'ask': 'How many locations, and does each have its own Google profile and phone line?',
     'say': 'It’s month to month. Core is $1,297 for the first location, and each extra location pack is $397 with its own Google profile, reviews and missed-call line. Would a number like that fit your budget?',
     'worry': '“Can I see one report across all my locations?”',
     'reply': 'I don’t want to promise something I can’t confirm. Station can answer that on its free 15-minute intro call at station.solutions/book, or by email at main@station.solutions.',
     'avoid': 'Usage over a product’s monthly allowance is billed extra after the first month, so don’t call the price fixed. Don’t estimate anything outside the published prices.'},
]

# Habits that win the call, in plain words, with the line to say and the line never to say.
PLAYBOOK = [
    {'t': 'Start with what it costs them, not with the product',
     'why': 'An owner feels a missed call as a lost job. Let them say it out loud and the product explains itself.',
     'say': 'When the phone rings and you can’t get to it, what happens to that caller?',
     'never': 'Opening with a list of what the product does.'},
    {'t': 'One problem, and the smallest thing that fixes it',
     'why': 'Fourteen products make people put off the decision. Ask one question, offer the one thing that fits, and let them add more later if they want.',
     'say': 'Sounds like the missed calls are the real problem, so let’s start there.',
     'never': 'Reading them every product, or starting with a plan at $1,297 or more.'},
    {'t': 'Make the first step small and reversible',
     'why': 'People say yes to what they can undo. Singles start at $47 a month and collections at $297, with a 14-day free trial and no contract.',
     'say': 'There’s no contract, and the first 14 days are free, so you can try it before you pay.',
     'never': 'Promising a trial on Core, Pro or Max, which have none. Or saying “no card needed,” which nobody has confirmed.'},
    {'t': 'Say who you are, then be straight about the commission',
     'why': 'Cold calls feel like scams. Name yourself and your reason, check it’s a good time, and say you’re paid a commission just before you ask for anything.',
     'say': 'Hi, it’s [your name], an independent partner with Station, calling about missed calls. Did I catch you at a bad time?',
     'never': 'Saying you work for Station, or hiding that you’re paid.'},
    {'t': 'Use their words, and say the product name like a name',
     'why': 'People trust what they recognize. “Texts back when you miss a call” lands. Product names said alone sound like grammar mistakes.',
     'say': 'Station’s Answer plan texts back anyone you miss.',
     'never': 'Jargon like “automation” or “workflow,” or a bare “Answer” or “Follow Up” in the middle of a sentence.'},
    {'t': 'Let them do the math on one job',
     'why': 'You don’t need to promise a return. Ask what a job is worth and how many calls go to voicemail, and they’ll compare it to the price themselves.',
     'say': 'What does an average job run you? About how many calls go to voicemail in a week? Station’s Answer plan is $297 a month. Does that math work for you?',
     'never': 'Saying it will pay for itself, or quoting numbers about other clients.'},
    {'t': 'Find who really decides',
     'why': 'The person on the phone is often not the one who approves. Mr. Chen asks his daughter. Karen asks the doctor. Rosa and Javier decide together.',
     'say': 'Who else weighs in on something like this? I can send the page to them too.',
     'never': 'Pushing for a yes from someone who needs a second person.'},
    {'t': 'Ask for one small next step, with a date',
     'why': 'The close is sending the page and getting an email. Name the day you’ll check back, so the call isn’t the end.',
     'say': 'I’ll send the page with the price so it’s in writing. What’s the best email? [stop] I’ll check back Thursday morning. Does 10 work?',
     'never': 'Asking for a decision on the first call, stacking two questions, or ending with no day.'},
    {'t': 'When they say “just send me an email”',
     'why': 'This is where most cold calls end. Find out what to send, and tie it to a day you’ll call back.',
     'say': 'Happy to. So I send the right page, is it missed calls, follow-up, or reviews? I’ll check back Thursday.',
     'never': 'Sending one generic page, or accepting a vague “sure” with no day to call back.'},
    {'t': 'Gatekeepers and voicemail',
     'why': 'Most dials end here. Be brief, get a name and the best time, and don’t pitch the person who answers.',
     'say': 'I’m calling the owner about missed calls. When’s the best time to catch them? On voicemail: “It’s [your name], an independent partner with Station, about missed calls. I’ll try again Thursday.”',
     'never': 'Saying they’re expecting your call, pitching the gatekeeper, or leaving a price on voicemail.'},
    {'t': 'Say one true, specific thing you saw',
     'why': 'Two minutes on their Google listing earns attention and makes the problem real. Ask about it, don’t accuse.',
     'say': 'Your Google listing shows closed on Saturdays. Is that right?',
     'never': 'Quoting a dollar loss, a statistic, or anything you didn’t actually see.'},
    {'t': 'When they say yes: three next steps',
     'why': 'Nothing is done on the call. Say what happens, stay out of the setup, and don’t promise a date.',
     'say': 'Great. Station emails you the checkout link and receipt, then you book a short onboarding call with your hours and Google link ready.',
     'never': 'Promising a go-live date, taking payment, or setting anything up yourself.'},
    {'t': 'A reflex “not interested” is not “do not call”',
     'why': '“Not interested” is often a reflex. One calm question is fair; if they say it again, stop. “Take me off your list” is absolute.',
     'say': 'No problem. Is it timing, or you’ve already got it covered?',
     'never': 'Arguing, asking twice, or calling back anyone who said do not call.'},
]
